---
- name: "Ensure /etc/sources.list.d exists"
  become: true
  file:
    path: /etc/sources.list.d
    state: directory
    mode: 0755
- name: "Ensure GnuPG is installed"
  become: true
  apt:
    name: gnupg
    state: present
- name: "Ensure the IntelliJ PPA is not present"
  become: true
  apt_repository:
    repo: ppa:mmk2410/intellij-idea
    state: absent
- name: "Ensure Jetbrains APT repo is present"
  become: true
  ansible.builtin.deb822_repository:
    name: jetbrains
    types: [deb]
    uris: "http://jetbrains-ppa.s3-website.eu-central-1.amazonaws.com"
    signed_by: "https://s3.eu-central-1.amazonaws.com/jetbrains-ppa/0xA6E8698A.pub.asc"
    suites: [any]
    components: [main]
    architectures: amd64
- name: "Ensure Spotify APT repo is present"
  become: true
  ansible.builtin.deb822_repository:
    name: spotify
    types: [deb]
    uris: "http://repository.spotify.com"
    # The following doesn't work, somehow:
    #signed_by: "https://download.spotify.com/debian/pubkey_6224F9941A8AA6D1.gpg"
    # Instead, I downloaded the key manually:
    # curl -fsSL https://download.spotify.com/debian/pubkey_6224F9941A8AA6D1.gpg
    # See https://www.spotify.com/us/download/linux/ for the latest key ID
    #
    # If APT cannot verify Spotify's key, check if their key has changed and update it below.
    signed_by: |-
      -----BEGIN PGP PUBLIC KEY BLOCK-----

      mQINBGc0vwABEADQtWcyZgno2mdh35eZDzL676CCFLwCnai5HcLTo9l1ZlcNPzvL
      ql6Fj63ZBpq9Y4Ucf6rqNo4uMIRJKC6ybVGhxzzyHijEXwhN+clFhFQPzZQEfyU/
      jEgiOL8R8rAkItlNeumkrvX5Q+TpSkQr8Yh518fMnbKtFnlKEI3Mu3XyDvisGjef
      1ES6HTAEbzHSbBAnp0+mzNPQ1NV5kJtRQ2S7eyd31rwRFKEBHzs8rgwti0af6OeH
      pnBiaWnB2KznRX1ZR2gU6pKFwx8oraaw876IL2WxpPyhwtDZP6rjtM+GIyd8BmWT
      GSOY82RCdaKT+w2/iJl6qYO2fBlphemH8imdhBGbAC1+oGnMjPxOHw6ClTV1aDm6
      nrovFsmyum6F9ou0qA32KIiy4sznPDpGsqIwRcSawDQS9PlCrV02RVtn6uk1Ylpu
      s/Fle29ia8cJDosYq4g+KNiC8Z1a4ripqQlSH/XXiem2iKW0C0S/VOE4v6HiON48
      zQBN/B7q4O+D95YehqboSp02gUQwLOUDk1+WrMDIHsQl76QXY9izrYy5caq9cZBy
      klGDC0SaEZGbNeKywa6GYejQxPuTBbeQY+CHZgxPkOd35KecighIgdWaI9uiXHEI
      wjod7zZVHvQWP20y160WNakYHRJUOUOIUY5C7Yl8cwafNuYJ+J6/ue5JOwARAQAB
      tDdTcG90aWZ5IFB1YmxpYyBSZXBvc2l0b3J5IFNpZ25pbmcgS2V5IDx0dXhAc3Bv
      dGlmeS5jb20+iQJUBBMBCAA+FiEEtCD9N3fM46fwB2tVyFZo32k3UAEFAmc0vwAC
      GwMFCQJRQwAFCwkIBwIGFQoJCAsCBBYCAwECHgECF4AACgkQyFZo32k3UAGSoxAA
      rS4ewvpj0vE9jp3qG7cAM5bIkU6H4/cWBED5/l9n/0kQhPTUeeNKE8T52rbdOard
      jd25J9CsyaItbDJ7LkE6acRm0V/qtmE7XwlrhLcCUe0qEyCeXWXtuGCiTpbBlZG/
      qJCP6AuiEGBmKlh9ToagMUM/yrng68pgVJXWe/b39GP21mrTDu3H56rXd7jrPO2n
      jzlxxhEJq9NxD8+PV5XUFefK2C35idgUhX1yWDEZ9YUBCYPwrBxTr0gEhcIhFZzo
      S30T3lG8oU7X97+Kk4QloiV4zsLH+7Aer/F1AMVRe+MVTlDwLlpnusKwAI+Syy3u
      aqKp2JGR14JmG3w/PsuzhqJ9rJC1UNYUY5tlIpy8Lje+PP7ag36DteSvzuHSNDMa
      feSk2Bve6UKng+zYq0dOLI7NiIQl7KZsHzSGzcskfx3wSdaVw7it3ssvoscul9mM
      uhqz4qoCXCXv4N2t49H1XgQtrZ54s/pJ4V9H2G/Xv85qKBrnlSi5xv43w6KbY1cX
      1upY90GkKwdhWZu+EueIXNvzA1VkquCSuLmlzUdnCZE7iNTRLDfm/A4afnC8f9K0
      z7qRIk/bCQAXTKngHPwd0qG3yD4z/a3F0W/+PNXIwCzCTC6/kr4goP6gxUkN5b2e
      TW2bDjIXULm9fpQsWJ0Y+/zCl69tZHtQ1Nop/3Nrl1M=
      =Muvn
      -----END PGP PUBLIC KEY BLOCK-----
    suites: [stable]
    components: [non-free]
    architectures: amd64
- name: "Ensure Visual Studio Code APT repo is present"
  become: true
  ansible.builtin.deb822_repository:
    name: vscode
    types: [deb]
    uris: "https://packages.microsoft.com/repos/code"
    signed_by: "https://packages.microsoft.com/keys/microsoft.asc"
    suites: [stable]
    components: [main]
    architectures: amd64
- name: "Ensure Seafile APT repo is present"
  become: true
  ansible.builtin.deb822_repository:
    name: seafile
    types: [deb]
    uris: "https://linux-clients.seafile.com/seafile-deb/{{ ansible_distribution_release }}/"
    signed_by: "https://linux-clients.seafile.com/seafile.asc"
    suites: [stable]
    components: [main]
    architectures: amd64
- name: "Ensure Signal APT repo is present"
  become: true
  ansible.builtin.deb822_repository:
    name: seafile
    types: [deb]
    uris: "https://updates.signal.org/desktop/apt"
    signed_by: "https://updates.signal.org/desktop/apt/keys.asc"
    suites: [xenial] # ["{{ ansible_distribution_release }}"]
    components: [main]
    architectures: amd64
