---
- name: "Ensure /etc/sources.list.d exists"
  become: true
  file:
    path: /etc/sources.list.d
    state: directory
    mode: 0755
- name: "Ensure GnuPG is installed"
  become: true
  apt:
    name: gnupg
    state: present
- name: "Ensure the IntelliJ PPA is not present"
  become: true
  apt_repository:
    repo: ppa:mmk2410/intellij-idea
    state: absent
- name: "Ensure Jetbrains APT repo is present"
  become: true
  ansible.builtin.deb822_repository:
    name: jetbrains
    types: [deb]
    uris: "http://jetbrains-ppa.s3-website.eu-central-1.amazonaws.com"
    signed_by: "https://s3.eu-central-1.amazonaws.com/jetbrains-ppa/0xA6E8698A.pub.asc"
    suites: [any]
    components: [main]
    architectures: amd64
- name: "Ensure Spotify APT repo is present"
  become: true
  ansible.builtin.deb822_repository:
    name: spotify
    types: [deb]
    uris: "http://repository.spotify.com"
    # The following doesn't work, somehow:
    #signed_by: "https://download.spotify.com/debian/pubkey_6224F9941A8AA6D1.gpg"
    # Instead, I downloaded the key manually:
    # curl -fsSL https://download.spotify.com/debian/pubkey_6224F9941A8AA6D1.gpg
    # See https://www.spotify.com/us/download/linux/ for the latest key ID
    signed_by: |-
      -----BEGIN PGP PUBLIC KEY BLOCK-----

      mQINBGVWABgBEACmyHqClhrPEupgMG5n14x1nKSSbqed9IDu5+m4vKve5gUlGLmg
      GqmlKjaIWaxKNsd0NrZ5b4tDE9/o2DLyI95f77zLavfmUqBHun3ksGnQcOTcnHLy
      bKuxxCMGOz4uPMdfZuilI9KoT5m/O49fCP23eYMlBiqtQ1zMgwM1dnwcrp8OLYDT
      e92AzE8Ghf1PMtkpXwOugMa1HimxSZ4mfoxf7TgkWtpHd3MvehJYXdO4FNE841rI
      zn/mSR57M9B22s6TEHFET7sajZsO3adtSZVeadYQAbHEQx+BxpWZ9Rd9ynQXvCbQ
      GMSLB6kR7H3rOSQzHENaR2esDJVoMMaV3ny26aQZLi4GtSR58zu6Tlbv9cSnEa19
      nXLJNfxB4u2ZlOpkHg1NjXXCcLLdkIUSvdXFEgBpAfUE1LSa+q6geQ/YJk18YRQz
      Uq0eL+avBlcze+z/vabvWaHGP3NTelUaksk3BxyRpOupn5xJHOyNZBwB2lEnBEwP
      xClJaVzN8seFh9Wq0zQmRFoYR8keVgKsC4KUT8ULHX+/rU8JptnM9X5SSGd1mv8i
      nT3BMu3KFdXtZHNYb6i9gvpvK2jRyqrZ3RvBKHXlA8Lk4PzHe8bC5qGmsjpd6Xgb
      kZKMoemHZe3vJ5dy5g3JQuzrKaks/wlWR65Vm8nDE/bd1dECqxxVprD74wARAQAB
      tDdTcG90aWZ5IFB1YmxpYyBSZXBvc2l0b3J5IFNpZ25pbmcgS2V5IDx0dXhAc3Bv
      dGlmeS5jb20+iQJUBBMBCgA+FiEEY8vuyQBmAgiPmxkyYiT5lBqKptEFAmVWABgC
      GwMFCQJRQwAFCwkIBwIGFQoJCAsCBBYCAwECHgECF4AACgkQYiT5lBqKptGIsw//
      cgeO0BVuOeAXyGdwoQaGnog8fyoNx/VkiX63BYB/J6HSIAnun0F4bImXa7kgScyX
      bPjPusTn7y4PEenqWl4Olaos9+B6U3vs1f0RHOCbbxtQUJOtVAFdfsRMWoxCviic
      0boW/5bFaDitBtuai8olbpb1YiA94uC+wGRXMWC3QOAwNPu9YWdon6IwJ4AFnEsS
      NpU3Vlyqrz4ZEwYm6FhW8cvoBHfOwJo3WQ1nKSXFBMSod58o97Lhr308wvIuev7X
      IgGeIZ1+zN39N7BLTaem9ynB8Fk0Mj9WGR+tztuQMcnZeL18rZNkMuzHx7UFY+ir
      GgusbpenRPRaqXpUGES2zPwxpUWIMV3fzoI045ktVNDHVqxcQ67DfQX+bgiUPcY5
      WaeEBSbpiqhqbqUjLtdTZtqyp1wMNHWxnQ4Bd9M2OipeKLThZ3sorFFZqVLmQ0Qs
      CNJ9fgHpCW2LFs4U3fMxyNxbgfTZ0fog5PlEw67bTDloFh6EuFS8gmr6quSaYhor
      1IjbJ8iex7lINqNUgZ4PDUYNnciLhYYgmvj8dKq1pZMPkZwTsGjtFnNJtlIE26qN
      sbbV1qADvxhOCZ9QjeQfT20FjaUYeBryh4KqRu2kTg8FTYdOXSINlunLgLk3qW5F
      IQkRR4+KWNraaGRySYGAGIIWc0Zzd8b6mIfJHcooAlc=
      =F5Ek
      -----END PGP PUBLIC KEY BLOCK-----
    suites: [stable]
    components: [non-free]
    architectures: amd64
- name: "Ensure Visual Studio Code APT repo is present"
  become: true
  ansible.builtin.deb822_repository:
    name: vscode
    types: [deb]
    uris: "https://packages.microsoft.com/repos/code"
    signed_by: "https://packages.microsoft.com/keys/microsoft.asc"
    suites: [stable]
    components: [main]
    architectures: amd64
- name: "Ensure Seafile APT repo is present"
  become: true
  ansible.builtin.deb822_repository:
    name: seafile
    types: [deb]
    uris: "https://linux-clients.seafile.com/seafile-deb/{{ ansible_distribution_release }}/"
    signed_by: "https://linux-clients.seafile.com/seafile.asc"
    suites: [stable]
    components: [main]
    architectures: amd64
- name: "Ensure Signal APT repo is present"
  become: true
  ansible.builtin.deb822_repository:
    name: seafile
    types: [deb]
    uris: "https://updates.signal.org/desktop/apt"
    signed_by: "https://updates.signal.org/desktop/apt/keys.asc"
    suites: [xenial] # ["{{ ansible_distribution_release }}"]
    components: [main]
    architectures: amd64
