---
- name: "Switch windows forward with Alt-Tab"
  shell: "gsettings set org.gnome.desktop.wm.keybindings switch-windows \"['<Alt>Tab']\""
- name: "Switch windows backward with Shift-Alt-Tab"
  shell: "gsettings set org.gnome.desktop.wm.keybindings switch-windows-backward \"['<Shift><Alt>Tab']\""
- name: "Switch applications forward with Super-Tab"
  shell: "gsettings set org.gnome.desktop.wm.keybindings switch-applications \"['<Super>Tab']\""
- name: "Switch applications backward with Shift-Super-Tab"
  shell: "gsettings set org.gnome.desktop.wm.keybindings switch-applications-backward \"['<Shift><Super>Tab']\""
# The next two settings remove combinations with Ctrl/Shift/Alt that are there by default
- name: "Switch workspaces left with Super-PageUp"
  shell: "gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-left \"['<Super>Page_Up']\""
- name: "Switch workspaces right with Super-PageDown"
  shell: "gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-right \"['<Super>Page_Down']\""
- name: "Disable move windows to workspace down"
  shell: "gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-down \"[]\""
- name: "Disable switch to workspace up"
  shell: "gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-up \"[]\""
# The next two settings remove combinations with Ctrl/Shift/Alt that are there by default
- name: "Move windows to workspace left with Super-Shift-PageUp"
  shell: "gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-left \"['<Super><Shift>Page_Up']\""
- name: "Move windows to workspace right with Super-Shift-PageDown"
  shell: "gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-right \"['<Super><Shift>Page_Down']\""
- name: "Disable move windows to workspace up"
  shell: "gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-up \"[]\""
- name: "Disable switch to workspace down"
  shell: "gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-down \"[]\""
- name: "Set number of workspaces to 2"
  shell: "gsettings set org.gnome.desktop.wm.preferences num-workspaces 2"
- name: "Disable Alt-F7 to move windows"
  shell: "gsettings set org.gnome.desktop.wm.keybindings begin-move \"[]\""
- name: "Disable Alt-F8 to resize windows"
  shell: "gsettings set org.gnome.desktop.wm.keybindings begin-resize \"[]\""
- name: "Minimize window when clicking on the dock icon"
  shell: "gsettings set org.gnome.shell.extensions.dash-to-dock click-action 'minimize'"
- name: "Do not show applications on other workspaces on the dock"
  shell: "gsettings set org.gnome.shell.extensions.dash-to-dock isolate-workspaces true"
- name: "Enable fractional scaling"
  shell: "gsettings set org.gnome.mutter experimental-features \"['x11-randr-fractional-scaling', 'scale-monitor-framebuffer']\""
- name: "Mute the microphone with Super-M"
  shell: "gsettings set org.gnome.settings-daemon.plugins.media-keys mic-mute \"['<Super>m']\""
- name: "Disable Super-S to toggle quick settings"
  shell: "gsettings set org.gnome.shell.keybindings toggle-quick-settings \"[]\""
- name: "Mute the volume with Super-S"
  shell: "gsettings set org.gnome.settings-daemon.plugins.media-keys volume-mute \"['<Super>s']\""
- name: "Disable Super-S to open the activities overview"
  shell: "gsettings set org.gnome.shell.keybindings toggle-overview \"[]\""
- name: "Play/pause with Ctrl-Alt-P"
  shell: "gsettings set org.gnome.settings-daemon.plugins.media-keys play \"['<Primary><Alt>p']\""
# This overwrites the default with the same value. If we don't, Super-M will also show the notifications list, for some reason.
- name: "Show the notifications list with Super-V"
  shell: "gsettings set org.gnome.shell.keybindings toggle-message-tray \"['<Super>v']\""
- name: "Do not show icon emblems"
  shell: "gsettings set org.gnome.shell.extensions.dash-to-dock show-icons-emblems false"
- name: "Do not show the Applications icon"
  shell: "gsettings set org.gnome.shell.extensions.dash-to-dock show-show-apps-button false"
- name: "Do not show the Trash icon"
  shell: "gsettings set org.gnome.shell.extensions.dash-to-dock show-trash false"

# Special
- name: "Noodkaart frustratie"
  shell: |
    gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ binding 'F1'
    gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ command 'xdg-open /home/wout/Seafile/wout/help/Frustratie.pdf'
    gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ name 'Noodkaart'
- name: "Connect custom shortcuts"
  shell: "gsettings set org.gnome.settings-daemon.plugins.media-keys custom-keybindings \"['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/']\""
