---
- name: "Ensure the IntelliJ PPA is not present"
  become: true
  apt_repository:
    repo: ppa:mmk2410/intellij-idea
    state: absent
- name: "Ensure /etc/sources.list.d exists"
  become: true
  file:
    path: /etc/sources.list.d
    state: directory
    mode: 0755
- name: "Ensure GnuPG is installed"
  become: true
  apt:
    name: gnupg
    state: present
- name: "Ensure Jetbrains APT key is present"
  become: true
  apt_key:
    url: https://s3.eu-central-1.amazonaws.com/jetbrains-ppa/0xA6E8698A.pub.asc
    state: present
- name: "Ensure Jetbrains APT repo is present"
  become: true
  apt_repository:
    repo: deb [signed-by=/usr/share/keyrings/jetbrains-ppa-archive-keyring.gpg] http://jetbrains-ppa.s3-website.eu-central-1.amazonaws.com any main
    state: present
    filename: jetbrains
    update_cache: yes
    validate_certs: no

# IntelliJ is not installed automatically, to give the user the option of installing it or something else (such as PyCharm).
