---
- name: "Ensure /home/{{ env_common_username }}/ exists"
  file:
    path: /home/{{ env_common_username }}/
    state: directory
    #owner: "{{ env_common_username }}"
    #group: "{{ env_common_username }}"

# Arrow keys and numpad
- name: "Make the arrow keys work in tree views (GTK 2)"
  blockinfile:
    dest: /home/{{ env_common_username }}/.gtkrc-2.0
    create: yes
    #owner: "{{ env_common_username }}"
    #group: "{{ env_common_username }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK - Tree view arrow keys"
    block: |
      binding "gtk-binding-tree-view" {
          bind "Left"     { "select-cursor-parent" ()
                            "expand-collapse-cursor-row" (0,0,0) }
          bind "Right"    { "expand-collapse-cursor-row" (0,1,0) }
      }
      class "GtkTreeView" binding "gtk-binding-tree-view"
- name: "Ensure /home/{{ env_common_username }}/.config/gtk-3.0 exists"
  file:
    path: /home/{{ env_common_username }}/.config/gtk-3.0
    state: directory
    #owner: "{{ env_common_username }}"
    #group: "{{ env_common_username }}"
- name: "Make the arrow keys work in tree views (GTK 3)"
  blockinfile:
    dest: /home/{{ env_common_username }}/.config/gtk-3.0/gtk.css
    create: yes
    #owner: "{{ env_common_username }}"
    #group: "{{ env_common_username }}"
    marker: "/* {mark} ANSIBLE MANAGED BLOCK - Tree view arrow keys */"
    block: |
      @binding-set GtkBindingTreeView
      {
          bind "Left"     {
                            "select-cursor-parent" ()
                            "expand-collapse-cursor-row" (0,0,0)
                          };
          bind "Right"    { "expand-collapse-cursor-row" (0,1,0) };
          bind "KP_Left"     {
                            "select-cursor-parent" ()
                            "expand-collapse-cursor-row" (0,0,0)
                          };
          bind "KP_Right"    { "expand-collapse-cursor-row" (0,1,0) };
      }
      GtkTreeView
      {
        gtk-key-bindings: GtkBindingTreeView;
      }
- name: "Make the numpad work like the way it works on Windows"
  become: true
  lineinfile:
    dest: /etc/default/keyboard
    create: yes
    owner: root
    group: root
    mode: "0644"
    regexp: ^XKBOPTIONS=
    line: XKBOPTIONS="numpad:microsoft"

# Custom keyboard layout
- name: "Ensure /etc/xkb subdirectories exist"
  become: true
  file:
    path: /etc/xkb/{{ item }}
    state: directory
    owner: root
    group: root
    mode: "0755"
  loop:
    - symbols
    - rules
- name: "Copy the custom keyboard layout definition to /etc/xkb/symbols/wout"
  become: true
  copy:
    src: keyboard_layout
    dest: /etc/xkb/symbols/wout
    owner: root
    group: root
    mode: "0644"
- name: "Register the custom keyboard layout in /etc/xkb/rules/evdev.xml"
  become: true
  copy:
    src: evdev.xml
    dest: /etc/xkb/rules/evdev.xml
    owner: root
    group: root
    mode: "0644"
# Can be removed once deployed everywhere
- name: "Remove the legacy layout file from /usr/share/X11/xkb"
  become: true
  file:
    path: /usr/share/X11/xkb/symbols/wout
    state: absent
