---
- name: "Ensure /home/{{ env_common_username }}/ exists"
  file:
    path: /home/{{ env_common_username }}/
    state: directory
    #owner: "{{ env_common_username }}"
    #group: "{{ env_common_username }}"
- name: "Make the arrow keys work in tree views (GTK 2)"
  blockinfile:
    dest: /home/{{ env_common_username }}/.gtkrc-2.0
    create: yes
    #owner: "{{ env_common_username }}"
    #group: "{{ env_common_username }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK - Tree view arrow keys"
    block: |
      binding "gtk-binding-tree-view" {
          bind "Left"     { "select-cursor-parent" ()
                            "expand-collapse-cursor-row" (0,0,0) }
          bind "Right"    { "expand-collapse-cursor-row" (0,1,0) }
      }
      class "GtkTreeView" binding "gtk-binding-tree-view"
- name: "Ensure /home/{{ env_common_username }}/.config/gtk-3.0 exists"
  file:
    path: /home/{{ env_common_username }}/.config/gtk-3.0
    state: directory
    #owner: "{{ env_common_username }}"
    #group: "{{ env_common_username }}"
- name: "Make the arrow keys work in tree views (GTK 3)"
  blockinfile:
    dest: /home/{{ env_common_username }}/.config/gtk-3.0/gtk.css
    create: yes
    #owner: "{{ env_common_username }}"
    #group: "{{ env_common_username }}"
    marker: "/* {mark} ANSIBLE MANAGED BLOCK - Tree view arrow keys */"
    block: |
      @binding-set GtkBindingTreeView
      {
          bind "Left"     {
                            "select-cursor-parent" ()
                            "expand-collapse-cursor-row" (0,0,0)
                          };
          bind "Right"    { "expand-collapse-cursor-row" (0,1,0) };
          bind "KP_Left"     {
                            "select-cursor-parent" ()
                            "expand-collapse-cursor-row" (0,0,0)
                          };
          bind "KP_Right"    { "expand-collapse-cursor-row" (0,1,0) };
      }
      GtkTreeView
      {
        gtk-key-bindings: GtkBindingTreeView;
      }
- name: "Make the numpad work like the way it works on Windows"
  become: true
  lineinfile:
    dest: /etc/default/keyboard
    create: yes
    owner: root
    group: root
    mode: 0644
    regexp: ^XKBOPTIONS=
    line: XKBOPTIONS="numpad:microsoft"
- name: "Ensure /usr/share/X11/xkb/ subdirectories exist"
  file:
    path: /usr/share/X11/xkb/{{ item }}/
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - symbols
    - rules
- name: "Copy the custom keyboard layout definition to symbols/wout"
  become: true
  copy:
    src: keyboard_layout
    dest: /usr/share/X11/xkb/symbols/wout
    owner: root
    group: root
    mode: 0644
- name: "Register the custom keyboard layout in rules/evdev.xml"
  become: true
  blockinfile:
    dest: /usr/share/X11/xkb/rules/evdev.xml
    create: no
    insertafter: "    <layoutList>"
    marker: "<!-- {mark} ANSIBLE MANAGED BLOCK - Custom keyboard layout -->"
    block: |
      <layout>
        <configItem>
          <name>wout</name>

          <shortDescription>English (US, Wout)</shortDescription>
          <description>English (US, Wout)</description>
        </configItem>
        <variantList>
        </variantList>
      </layout>
- name: "Compile the keyboard layout data"
  become: true
  shell: "dpkg-reconfigure xkb-data"
