---
#- import_tasks: gtk.yml
- import_tasks: gnome.yml
- import_tasks: keyboard.yml
- import_tasks: apt-repos.yml
- import_tasks: software.yml
- import_tasks: git.yml
- name: "Ensure ~/dev exists"
  become: true
  file:
    path: /home/{{ env_common_username }}/dev
    state: directory
    owner: "{{ env_common_username }}"
    group: "{{ env_common_username }}"
    mode: 0755
- name: "Check out the notes repository"
  git:
    repo: https://scheleaap@github.com/scheleaap/dev-notes.git
    dest: /home/{{ env_common_username }}/dev/dev-notes
    version: master
- name: "Ensure crash report popups are disabled"
  become: true
  lineinfile:
    dest: /etc/default/apport
    regexp: ^enabled=
    line: enabled=0
