---
- name: "Refresh apt cache"
  become: true
  apt:
    update_cache: true
- name: "Install desktop packages"
  become: true
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - chromium-browser
      - doublecmd-gtk
      - exfat-fuse
      - exfat-utils
      - fonts-roboto
      - gitg
      - gnome-tweak-tool
      - thunderbird
      - ttf-mscorefonts-installer
      - workrave
