---
- name: "Install desktop packages (APT)"
  become: true
  apt:
    name: "{{ packages }}"
    update_cache: true
  vars:
    packages:
      - baobab
      - btop
      - chromium-browser
      - code
      - dconf-editor
      - digikam
      - dos2unix
      - dosfstools
      - doublecmd-gtk
      - exfatprogs
      - fonts-roboto
      - gimp
      - gitg
      - gnome-shell-extensions
      - gnome-tweaks
      - gparted
      - gpick
      - guvcview
      - inkscape
      - mtools
      - seafile-gui
      - signal-desktop
      - spotify-client
      - thunderbird
      - ttf-mscorefonts-installer
      - ubuntu-restricted-extras
      - workrave
      - workrave-gnome
- name: "Install desktop packages (Snap)"
  become: true
  snap:
    name: "{{ packages }}"
  vars:
    packages:
      - vlc
- name: "Ensure ~/.config/autostart exists"
  become: true
  file:
    path: /home/{{ env_common_username }}/.config/autostart
    state: directory
    owner: "{{ env_common_username }}"
    group: "{{ env_common_username }}"
    mode: 0755
- name: "Enable autostart"
  template:
    src: templates/autostart.desktop.j2
    dest: /home/{{ env_common_username }}/.config/autostart/{{ item.name }}.desktop
  loop:
    - name: Workrave
      command: workrave
    - name: Seafile
      command: seafile-applet
