---
- name: "Ensure the IntelliJ PPA is present"
  become: true
  apt_repository:
    repo: ppa:mmk2410/intellij-idea
- name: "Refresh apt cache"
  become: true
  apt:
    update_cache: true
- name: "Install desktop packages"
  become: true
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - exfat-fuse
      - exfat-utils
      - chromium-browser
      - thunderbird
      - gitg
      - intellij-idea-community
      - workrave
