---
- name: "Check whether Unity is installed"
  command: dpkg-query -W -f='${Status}' unity | grep 'install ok installed'
  register: unity_check
  failed_when: no
  changed_when: no
- name: "Check whether Unity 2D is installed"
  command: dpkg-query -W -f='${Status}' unity-2d | grep 'install ok installed'
  register: unity_2d_check
  failed_when: no
  changed_when: no
- name: "Always show menus in Ubuntu"
  shell: "gsettings set com.canonical.Unity always-show-menus true"
  when:
    - unity_check.rc == 0 or unity_2d_check.rc == 0
- name: "Use local menus in Ubuntu"
  shell: "gsettings set com.canonical.Unity integrated-menus false"
  when:
    - unity_check.rc == 0 or unity_2d_check.rc == 0
